source 'https://rubygems.org'

gem 'jekyll', '~> 4.3'
gem 'nokogiri', '~> 1.19'
gem 'jekyll-sass-converter', '~> 2.2'
gem 'rake'
gem 'rouge', '~> 4.0'
gem 'html-proofer', '~> 4.4'
gem 'jemoji', '~> 0.13'
gem 'jekyll-mentions', '~> 1.1'
gem 'jekyll-seo-tag', '~> 2.8'
gem 'jekyll-feed', '~> 0.17'
gem 'jekyll-sitemap', '~> 1.4'
gem 'jekyll-gist', '~> 1.5'
gem 'jekyll-paginate', '~> 1.1'
